weixin:
  appid: wxc5c699af7ce21427
  appsecret: 32e0827fdaa943f3405323f27114116e
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WeChat_2022
    url: jdbc:mysql://sh-cynosdbmysql-grp-2v5jxp98.sql.tencentcdb.com:26135/nnt?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
elasticsearch:
  host: 139.196.157.116
  port: 9200
